apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}
    spec:
      containers:
        - name : {{ .Release.Name }}-app
          image: {{ .Values.app.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 800Mi
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 3
          env:
            - name: DB_HOST
              valueFrom: 
                configMapKeyRef:
                  name: db-config
                  key: db-host
            - name: DB_PORT
              valueFrom: 
                configMapKeyRef:
                  name: db-config
                  key: db-port
            - name: DB_NAME
              valueFrom: 
                configMapKeyRef:
                  name: db-config
                  key: db-name
            - name: DB_USERNAME
              valueFrom: 
                secretKeyRef:
                  name: todo-secret
                  key: db-user
            - name: DB_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: todo-secret
                  key: db-pass
